### ISSUE TITLE
Events Volunteers Abends

### ISSUE THREAD

**Issue by mdchafin** [GregFinzer/BedBrigadeNational#298]
![image](https://github.com/GregFinzer/BedBrigadeNational/assets/4579684/eabf5321-67c1-4cba-b4ee-3653b34be577)

When trying to use the Event Volunteers the program abends.

blazor.server.js:1 [2023-10-22T12:44:56.192Z] Error: System.ArgumentNullException: Value cannot be null. (Parameter 'outer')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Join[TOuter,TInner,TKey,TResult](IEnumerable`1 outer, IEnumerable`1 inner, Func`2 outerKeySelector, Func`2 innerKeySelector, Func`3 resultSelector)
   at BedBrigade.Client.Components.EvolHelper.GetGridDataSource(List`1 VolunteerEvents, List`1 Schedules, List`1 Volunteers, List`1 Locations) in C:\Development\Git\BedBrigadeNational\BedBrigade.Client\Components\EvolHelper.cs:line 97
   at BedBrigade.Client.Components.EvolGrid.PrepareGridData() in C:\Development\Git\BedBrigadeNational\BedBrigade.Client\Components\EvolGrid.razor.cs:line 248
   at BedBrigade.Client.Components.EvolGrid.OnInitializedAsync() in C:\Development\Git\BedBrigadeNational\BedBrigade.Client\Components\EvolGrid.razor.cs:line 114
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by nidroks** [comment]
The file EvolHelper.cs was modified to fix this issue, related to empty database tables

**Comment by mdchafin** [comment]
The fix has not been pushed.

**Comment by mdchafin** [comment]
This is fixed.
